resolvers:
    - 1.1.1.1
    - 1.0.0.1
    - 8.8.8.8
    - 8.8.4.4
    - 9.9.9.9
    - 9.9.9.10
    - 77.88.8.8
    - 77.88.8.1
    - 208.67.222.222
    - 208.67.220.220
sources:
    - alienvault
    - anubis
    - bufferover
    - certspotter
    - censys
    - chaos
    - crtsh
    - dnsdumpster
    - hackertarget
    - intelx
    - passivetotal
    - robtex
    - securitytrails
    - shodan
    - threatcrowd
    - threatminer
    - virustotal
all-sources:
    - alienvault
    - anubis
    - archiveis
    - binaryedge
    - bufferover
    - censys
    - certspotter
    - chaos
    - commoncrawl
    - crtsh
    - dnsdumpster
    - dnsdb
    - github
    - hackertarget
    - intelx
    - passivetotal
    - rapiddns
    - recon
    - robtex
    - securitytrails
    - shodan
    - sitedossier
    - sonarsearch
    - threatbook
    - threatcrowd
    - threatminer
    - virustotal
    - waybackarchive
    - zoomeye
recursive:
    - alienvault
    - binaryedge
    - bufferover
    - certspotter
    - crtsh
    - dnsdumpster
    - hackertarget
    - passivetotal
    - securitytrails
    - sonarsearch
    - virustotal
bevigil: []
binaryedge: []
bufferover: []
c99: []
censys: []
certspotter: []
chaos: []
chinaz: []
dnsdb: []
dnsrepo: []
facebook: []
fofa: []
fullhunt: []
github: []
hunter: []
intelx: []
leakix: []
netlas: []
passivetotal: []
quake: []
robtex: []
securitytrails: []
shodan: [d8GXZfOOQH0WvuAIa1Ucbob3CbIIsO4J]
threatbook: []
virustotal: []
whoisxmlapi: []
zoomeye: [C168dA68-CB4D-0C586-7707-D066812485f]
zoomeyeapi: [C168dA68-CB4D-0C586-7707-D066812485f]
#subfinder-version: 2.4.8
